# =================================================================
#  RV Intelligence Device
#  Emmanuel Loria, Jordan Krause, Maya Hampton
#  Date 2/10/2025
#  yaml file that reads water tank level and temperature from Mopeka
#  https://esphome.io/components/sensor/mopeka_pro_check
#     > esphome documentation to read data from sensor
# =================================================================

esphome:
  name: mopeka_ble
  platform: ESP32
  board: esp32dev

esp32_ble_tracker:

sensor:
  - platform: mopeka_pro_check
    mac_address: D3:89:69:6E:82:DC
    tank_type: CUSTOM
    custom_distance_full: 11.1cm
    custom_distance_empty: 1mm
    level:
        name: "Propane Level"
logger:
